-- Отступ новой строки (config.sqlindent): последняя строка текста — та, что набирается.

local t = require("helpers")
local describe, it, eq = t.describe, t.it, t.eq

local ind = require("config.sqlindent")

local function indent(src)
  local lines = vim.split(src, "\n", { plain = true })
  return ind.compute(function(l)
    return lines[l]
  end, #lines, 2)
end

describe("блоки", function()
  it("после begin и AS BEGIN — уровень глубже", function()
    eq(2, indent("AS BEGIN\n"))
    eq(4, indent("  if @a = 1\n  begin\n"))
    eq(4, indent("  begin try\n"))
    eq(4, indent("  end else\n  begin\n"))
  end)
  it("begin tran блок не открывает", function()
    eq(2, indent("  begin tran\n"))
  end)
  it("begin под if — на уровне if", function()
    eq(2, indent("  if @a = 1\nbegin"))
  end)
  it("end — под своим begin, вложенные пропускаются", function()
    eq(2, indent("  begin\n    if @a = 1\n    begin\n      set @a = 2\n    end\n    set @b = 1\n    end"))
    eq(0, indent("AS BEGIN\n  set @a = 1\n  end"))
  end)
  it("end от case — в колонку case", function()
    eq(4, indent("  set @a =\n    case\n      when 1 = 1 then 1\n  end"))
  end)
  it("строка после end — на его уровне", function()
    eq(2, indent("  begin\n    set @a = 1\n  end\n"))
  end)
  it("комментарий после begin не мешает", function()
    eq(4, indent("  begin -- ветка\n"))
  end)
  it("пустые строки пропускаются", function()
    eq(4, indent("  begin\n\n"))
  end)
end)

describe("списки", function()
  it("select / declare одни — первый элемент на +3", function()
    eq(5, indent("  select\n"))
    eq(5, indent("  declare\n"))
  end)
  it("запятая — на +2 от открывшей строки, дальше под запятой", function()
    eq(4, indent("  select\n     a\n,"))
    eq(4, indent("  select\n     a\n    ,b\n,"))
    eq(2, indent("CREATE PROCEDURE [dbo].[x]\n   @a int\n,"))
  end)
  it("параметры процедуры — на +3", function()
    eq(3, indent("CREATE PROCEDURE [dbo].[x]\n"))
    eq(3, indent("CREATE OR ALTER PROCEDURE dbo.x\n"))
    eq(0, indent("CREATE PROCEDURE dbo.x AS\n"))
  end)
  it("AS BEGIN после параметров — в колонку CREATE", function()
    eq(0, indent("CREATE PROCEDURE [dbo].[x]\n   @a int\n  ,@b int\nAS BEGIN"))
    eq(4, indent("    set @a = 1\n    as"), "без заголовка — не трогаем")
  end)
  it(
    "после скобки — глубже, закрывающая — на уровне открывшей строки",
    function()
      eq(4, indent("  insert into T(\n"))
      eq(4, indent("  using\n    (select\n        a = 1\n      ,b = 2\n)"))
    end
  )
end)

describe("клаузы", function()
  it("from / where — в колонку select", function()
    eq(2, indent("  select\n     a\n    ,b\nfrom"))
    eq(2, indent("  select a\n    from T\n    where"))
  end)
  it("подзапрос в скобках пропускается", function()
    eq(2, indent("  select a, (select 1 from X)\nfrom"))
  end)
  it("from внутри скобок — к select в скобке", function()
    eq(13, indent("  if exists (select 1\nfrom"))
  end)
  it(
    "после подзапроса, закрытого в хвосте строки, — уровень его конструкции (S48)",
    function()
      local q = "from chtRooms r\n  outer apply (\n    select\n      UnreadCount = COUNT(1)\n"
        .. "    from chtMessages ms\n    where ms.chtrID = r.chtrID\n      and ms.IsDeleted = 0) unr\n"
      eq(2, indent(q))
      eq(0, indent("if not exists (\n  select 1\n  from T\n  where a = @a)\n"))
      eq(2, indent("  set @a = ISNULL(@b, 0)\n"), "скобки в строке сбалансированы")
    end
  )
  it("без select — отступ предыдущей строки", function()
    eq(4, indent("    set @a = 1\nfrom"))
    eq(4, indent("  select a from T\n  begin\n    set @a = 1\nfrom"), "select за begin — чужой")
  end)
end)
